# Generated by Django 4.2.4 on 2023-09-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_version_product_vers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='prod',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vers',
        ),
    ]
